---
- name: Create Wazuh directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ wazuh_docker_dir }}"
    - "{{ wazuh_docker_dir }}/volumes/wazuh-indexer/config"
    - "{{ wazuh_docker_dir }}/volumes/wazuh-manager/config"
    - "{{ wazuh_docker_dir }}/volumes/wazuh-dashboard/config"
    - "{{ wazuh_docker_dir }}/volumes/wazuh-indexer/data"
    - "{{ wazuh_docker_dir }}/volumes/wazuh-manager/data"
    - "{{ wazuh_docker_dir }}/certs"

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ wazuh_docker_dir }}/docker-compose.yml"
    mode: '0644'

- name: Copy generate-certs.sh script
  template:
    src: generate-certs.sh.j2
    dest: "{{ wazuh_docker_dir }}/certs/generate-certs.sh"
    mode: '0755'

- name: Copy .env file
  template:
    src: env.j2
    dest: "{{ wazuh_docker_dir }}/.env"
    mode: '0644'

- name: Generate certificates
  command: "{{ wazuh_docker_dir }}/certs/generate-certs.sh"
  args:
    chdir: "{{ wazuh_docker_dir }}/certs"
    creates: "{{ wazuh_docker_dir }}/certs/wazuh-certificates.tar"

- name: Extract certificates
  unarchive:
    src: "{{ wazuh_docker_dir }}/certs/wazuh-certificates.tar"
    dest: "{{ wazuh_docker_dir }}/certs"
    remote_src: yes
    creates: "{{ wazuh_docker_dir }}/certs/root-ca.key"

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull Docker images
  command: "docker-compose -f {{ wazuh_docker_dir }}/docker-compose.yml pull"
  args:
    chdir: "{{ wazuh_docker_dir }}"
  register: docker_pull
  changed_when: docker_pull.rc == 0

- name: Start Wazuh Docker containers
  command: "docker-compose -f {{ wazuh_docker_dir }}/docker-compose.yml up -d"
  args:
    chdir: "{{ wazuh_docker_dir }}"
  register: docker_up
  changed_when: docker_up.rc == 0

- name: Wait for Wazuh Dashboard to be available
  uri:
    url: "https://{{ inventory_hostname }}:{{ wazuh_dashboard_port }}"
    validate_certs: no
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  ignore_errors: yes

- name: Display Wazuh Dashboard access information
  debug:
    msg: 
      - "Wazuh installation completed!"
      - "Access Wazuh Dashboard at https://{{ inventory_hostname }}:{{ wazuh_dashboard_port }}"
      - "Default username: {{ wazuh_admin_user }}"
      - "Default password: {{ wazuh_admin_password }}"