---
# Default variables for the splunk forwarder role.
splunk_version: "9.1.1"
splunk_build: "64e843ea36b1"
splunk_package_tgz: "splunkforwarder-{{ splunk_version }}-{{ splunk_build }}-Linux-x86_64.tgz"
splunk_download_url: "https://download.splunk.com/products/universalforwarder/releases/{{ splunk_version }}/linux/{{ splunk_package_tgz }}"
splunk_install_dir: "/opt/splunkforwarder"
splunk_indexer_ip: "172.20.241.20"
splunk_receiver_port: "9997"
splunk_admin_username: "admin"
splunk_admin_password: "Changeme1!"

# Create Splunk user
splunk_create_user: true

# Enable boot-start
splunk_enable_boot_start: true