---
- name: Restart Splunk
  ansible.builtin.service:
    name: "{% if ansible_os_family == 'RedHat' %}SplunkForwarder{% else %}splunk{% endif %}"
    state: restarted
  become: true
  register: restart_result
  retries: 3
  delay: 10
  until: restart_result is succeeded

- name: Reload Systemd
  ansible.builtin.systemd:
   daemon_reload: true
  become: true
