---
# ansible/roles/wazuh-agent/vars/Debian.yml

# Package information
wazuh_agent_package: "wazuh-agent"

# Configuration paths
wazuh_agent_config_dir: "/var/ossec/etc"
wazuh_agent_binary: "/var/ossec/bin/agent-auth"
wazuh_agent_service: "wazuh-agent"

# Log collection for Debian/Ubuntu
wazuh_agent_linux_logs:
  - "/var/log/auth.log"
  - "/var/log/syslog"
  - "/var/log/dpkg.log"
  - "/var/log/apt/history.log"
  - "/var/log/apt/term.log"
  - "/var/log/kern.log"
  - "/var/log/fail2ban.log"
  - "/var/log/apache2/*.log"
  - "/var/log/nginx/*.log"
  - "/var/log/mysql/*.log"
  - "/var/log/postgresql/*.log"

# Debian-specific monitored files
wazuh_agent_linux_monitored_files:
  - "/etc/passwd"
  - "/etc/shadow"
  - "/etc/group"
  - "/etc/sudoers"
  - "/etc/ssh/sshd_config"
  - "/etc/apt/sources.list"
  - "/etc/apt/sources.list.d/*"
  - "/etc/resolv.conf"
  - "/etc/crontab"
  - "/etc/cron.d/*"
  - "/etc/apache2/apache2.conf"
  - "/etc/nginx/nginx.conf"
  - "/var/www/html/index.*"