---
# ansible/roles/wazuh-agent/vars/RedHat.yml

# Package information
wazuh_agent_package: "wazuh-agent"

# Configuration paths
wazuh_agent_config_dir: "/var/ossec/etc"
wazuh_agent_binary: "/var/ossec/bin/agent-auth"
wazuh_agent_service: "wazuh-agent"

# Log collection for RHEL/CentOS/Fedora
wazuh_agent_linux_logs:
  - "/var/log/messages"
  - "/var/log/secure"
  - "/var/log/audit/audit.log"
  - "/var/log/yum.log"
  - "/var/log/dnf.log"
  - "/var/log/httpd/*"
  - "/var/log/mariadb/mariadb.log"
  - "/var/log/mysql/mysql.log"
  - "/var/log/fail2ban.log"
  - "/var/log/maillog"
  - "/var/log/cron"
  - "/var/log/boot.log"

# RHEL-specific monitored files
wazuh_agent_linux_monitored_files:
  - "/etc/passwd"
  - "/etc/shadow"
  - "/etc/group"
  - "/etc/sudoers"
  - "/etc/ssh/sshd_config"
  - "/etc/yum.repos.d/*"
  - "/etc/resolv.conf"
  - "/etc/crontab"
  - "/etc/cron.d/*"
  - "/etc/httpd/conf/httpd.conf"
  - "/etc/nginx/nginx.conf"
  - "/var/www/html/index.*"
  - "/etc/my.cnf"
  - "/etc/pki/tls/private/*"