- name: Configure forwarder to send logs to indexer
  command: "{{ splunk_install_dir }}/bin/splunk add forward-server {{ splunk_indexer_ip }}:{{ splunk_receiver_port }} -auth {{ splunk_admin_username }}:{{ splunk_admin_password }}"
  become: true
  become_user: splunk
  register: forward_server
  changed_when: "'Added forwarding to: {{ splunk_indexer_ip }}:{{ splunk_receiver_port }}' in forward_server.stdout"
  failed_when:
    - forward_server.rc != 0
    - "'already exists' not in forward_server.stderr"
  notify: restart splunk