- name: Create temporary download directory
  file:
    path: /tmp/splunk_install
    state: directory
    mode: '0755'
  become: true

- name: Download Splunk Universal Forwarder package
  get_url:
    url: "{{ splunk_download_url }}"
    dest: "/tmp/splunk_install/{{ splunk_package_tgz }}"
    mode: '0644'
  become: true
  register: download_result
  retries: 3
  delay: 5
  until: download_result is succeeded

- name: Extract Splunk Universal Forwarder
  unarchive:
    src: "/tmp/splunk_install/{{ splunk_package_tgz }}"
    dest: /opt
    remote_src: yes
    creates: "{{ splunk_install_dir }}/bin"
  become: true
  notify: restart splunk

- name: Set ownership of Splunk directory
  file:
    path: "{{ splunk_install_dir }}"
    owner: splunk
    group: splunk
    recurse: yes
  become: true
  when: splunk_create_user | bool

- name: Create user-seed.conf for admin credentials
  template:
    src: user-seed.conf.j2
    dest: "{{ splunk_install_dir }}/etc/system/local/user-seed.conf"
    owner: splunk
    group: splunk
    mode: '0644'
  become: true
  notify: restart splunk

- name: Start and accept license
  command: "{{ splunk_install_dir }}/bin/splunk start --accept-license --answer-yes --no-prompt"
  become: true
  args:
    creates: "{{ splunk_install_dir }}/etc/users"
  register: splunk_start
  changed_when: "'successfully' in splunk_start.stdout"
  failed_when: 
    - splunk_start.rc != 0
    - "'already' not in splunk_start.stderr"

- name: Enable boot-start
  command: "{{ splunk_install_dir }}/bin/splunk enable boot-start"
  become: true
  args:
    creates: /etc/systemd/system/SplunkForwarder.service
  register: enable_bootstart
  changed_when: "'successfully' in enable_bootstart.stdout"
  when: splunk_enable_boot_start | bool
  notify: reload systemd
