---
# Main tasks file for Splunk Universal Forwarder
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "main.yml"

- name: Create splunk group
  group:
    name: splunk
    state: present
  become: true
  when: splunk_create_user | bool

- name: Create splunk user
  user:
    name: splunk
    group: splunk
    home: "{{ splunk_install_dir }}"
    shell: /bin/false
    system: true
    create_home: false
    state: present
  become: true
  when: splunk_create_user | bool

- name: Include installation tasks
  include_tasks: install.yml

- name: Include configuration tasks
  include_tasks: config.yml

- name: Include monitor configuration tasks
  include_tasks: monitors.yml

- name: Apply OS-specific fixes
  include_tasks: "{{ ansible_distribution | lower }}_fixes.yml"
  when: ansible_distribution | lower in ['centos', 'fedora']
