---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.fail2ban
    # https://github.com/robertdebock/ansible-role-fail2ban
  vars:
      fail2ban_configuration: []
      #  - option: loglevel
      #    value: "INFO"
      #    section: Definition

      fail2ban_jail_configuration: []
      #  - option: ignoreself
      #    value: "true"
      #    section: DEFAULT

      # Path to directory containing filters to copy in filter.d
      # fail2ban_filterd_path:

