---
- name: Install NTP on applicable servers
  hosts: all
  become: true
  roles:
    - geerklingguy.ntp
  vars:
    ntp_timezone: America/Chicago
#   ntp_manage_config: true
#   ntp_restrict:
#     - "172.20.242.200"
#     - "172.20.240.20"  

  # https://github.com/geerlingguy/ansible-role-ntp
