---
- name: Harden SSH configuration
  hosts: all
  become: true
  roles:
    - devsec.hardening.ssh_hardening
  vars:
    ssh_permit_root_login: "no"
    ssh_allow_agent_forwarding: false
    ssh_allow_tcp_forwarding: "no"
    ssh_max_auth_retries: 4
    ssh_max_sessions: 2
    ssh_max_startups: "5:20:30"
    ssh_client_port: 51245
    ssh_client_alive_interval: 300
    ssh_client_alive_count: 3
    sshd_custom_options:
      - "AcceptEnv LANG"
      - "LogLevel VERBOSE"
      - "MaxStartups 10:30:60"
      - "AllowUsers CCDCIR"
    sftp_enabled: false  # Ensure Ansible can transfer files via SCP
