---
# ansible/playbooks/deploy_wazuh.yml

- name: Deploy Wazuh server
  hosts: wazuh_servers
  become: true
  gather_facts: true
  
  vars:
    # Override default values here if needed
    wazuh_version: "4.5.2"
    wazuh_admin_user: "admin"
    wazuh_admin_password: "ChangeMe2025!" # Change this to a secure password
    wazuh_dashboard_port: 443
    wazuh_api_port: 55000
    wazuh_indexer_heap_size: "4g" # Adjust based on available memory
    wazuh_dashboard_heap_size: "2g" # Adjust based on available memory
    wazuh_manager_heap_size: "2g" # Adjust based on available memory
  
  roles:
    - wazuh-server