---
# use `ansible-galaxy install -r requirements.yml`

# Collections
collections:
  # https://galaxy.ansible.com/ui/repo/published/devsec/hardening/docs/
  # Includes the ssh hardening role
  - name: devsec.hardening
    # https://galaxy.ansible.com/ui/repo/published/devsec/hardening/docs/

# Roles
roles:
  - name: robertdebock.fail2ban
    version: "5.0.6"

  - name: geerlingguy.ntp
    version: "2.3.0"
    
  - name: geerlingguy.security
    version: "2.1.0"  

  # Splunk manager role (from splunk!)
  - name: splunk
    src: https://github.com/splunk/ansible-role-for-splunk
    version: v2.1.4 
