---

# Wazuh version and repository information
wazuh_agent_version: "4.5.2"
wazuh_agent_repo_version: "4.x"

# Wazuh manager connection settings
wazuh_server_ip: "172.20.241.20"  # Default to the Splunk IP from your inventory
wazuh_manager_port: 1514
wazuh_registration_port: 1515
wazuh_registration_password: ""  # Set this if using password-based registration

# Agent configuration settings
wazuh_agent_register: true
wazuh_agent_service_enabled: true
wazuh_agent_verify_host_cert: false
wazuh_agent_verify_manager_cert: false

# Agent monitoring and security configuration
wazuh_agent_syscheck_frequency: 43200  # 12 hours
wazuh_agent_rootcheck_enabled: true
wazuh_agent_wodle_openscap_enabled: true
wazuh_agent_wodle_cis_cat_enabled: true
wazuh_agent_command_monitoring_enabled: true
wazuh_agent_file_monitoring_enabled: true
wazuh_agent_syscollector_enabled: true

# Monitored directories and files
wazuh_agent_monitored_directories:
  - { path: "/etc", check_all: "yes" }
  - { path: "/usr/bin", check_all: "yes" }
  - { path: "/usr/sbin", check_all: "yes" }
  - { path: "/bin", check_all: "yes" }
  - { path: "/sbin", check_all: "yes" }
  - { path: "/boot", check_all: "yes" }
  - { path: "/var/log", check_all: "yes" }

# Windows-specific directories to monitor (if applicable)
wazuh_agent_windows_monitored_directories:
  - { path: "C:\\Windows\\System32", check_all: "yes" }
  - { path: "C:\\Program Files", check_all: "yes" }
  - { path: "C:\\Program Files (x86)", check_all: "yes" }
  - { path: "C:\\Windows", check_all: "yes" }

# Log collection settings
wazuh_agent_log_alert_level: 3
wazuh_agent_email_notification: false
wazuh_agent_email_to: "root@localhost"
wazuh_agent_email_from: "wazuh@localhost"
wazuh_agent_email_smtp_server: "localhost"

# Monitored ports
wazuh_agent_monitored_ports:
  - protocol: "tcp"
    port_range: "1-65535"
